### ISSUE TITLE
Don't fail builds on failed reachability test

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install-updater-go#14]
Do you think we should make builds still pass even when the reachability test fails (as it prevents the deployment)? The updater will still keep track of the failures in the commit messages (like [this one](https://github.com/just-install/registry/commit/f92108af5ed5b743ac7e74c36e422123ab6e3d12)), but then we wouldn't get notified of a failed build if something breaks.

The advantage of this would be that we can ignore the errors, as most are temporary server errors which resolve themselves quite fast. The main disadvantage would be a small risk of jiup-go committing a broken URL (but that could be fixed by improving the tests on the registry repo, and only deploying successful tests).

cc @lvillani

**Comment by geek1011** [comment]
@lvillani?

**Comment by lvillani** [comment]
I'm not sure. Ignoring errors would have the potential for false negatives. How many errors are we talking about? Is it possible to make reachability tests more resilient, i.e. with repeated checks w/ exponential back-off? It would probably make sense to add the ability to ignore errors on particular hosts that end up being particularly problematic.

**Comment by geek1011** [comment]
I have decided to keep it as-is.

**Comment by geek1011** [comment]
What do you think about making it not count as a failure if `TRAVIS_EVENT_TYPE` is cron?

**Comment by lvillani** [comment]
I'm wondering whether having different failure modes between cron and non-cron builds may have an impact on "debuggability" whilst trying to find out why an host is failing. I think it would make sense to try this route and revert in case it creates more problems than it solves.

OT: does AppVeyor expose the same kind of environment variable, in case we switch to it (didn't check the docs yet)?

**Comment by geek1011** [comment]
Ok. And actually, now that I think about it, not failing for manually triggered builds seems an even better idea.

As for AppVeyor, it has APPVEYOR_SCHEDULED_BUILD and APPVEYOR_FORCED_BUILD.

**Comment by Hattshire** [comment]
Wouldn't it be better to have a deploy branch which updates the registry no matter if a host is unreliable or not and a develop branch for new, not yet tested updater scripts for at least one version change?

Generating a reachability error report and exporting it on gist would be better in my opinion.

Also, wouldn't it be checking things like
**_[u'paint.net' does not match any of the regexes: u'^[a-zA-Z0-9\\-\\+]+$'](https://ci.appveyor.com/project/lvillani/registry/builds/24227694#L26)_**
?
Checking the reachy is important, but it's keeping some apps outdated, for example the php in registry gives 404 due to the archival of old versions the source has, however it's updater script gets the newer link correctly but it doesn't get deployed.

**Comment by geek1011** [comment]
I've finished switching everything over to AppVeyor. I've also made HTTP timeouts not count as errors, as they happen in about 75% of the builds, and are intermittent. This should fix the issues with outdated apps.

As for the reachability report, there's a log of the link and version extraction errors attached in the commit messages on the registry. I could modify it to also add link testing, but that's currently handled by jiup itself (@lvillani?).

Can you elaborate on what your idea for the difference between the deploy branch would be?
